import { mkdirSync, writeFileSync } from "node:fs";
import { join } from "node:path";

/**
 * How a generated shim re-enters kiri: the executable to exec and — when
 * running from source — the entry script to pass it.
 */
export interface ShimTarget {
  execPath: string;
  main: string;
}

// Compiled Bun binaries report their entry under this virtual prefix; its
// presence means execPath alone is the kiri binary and takes the command
// directly, with no entry-script argument.
const BUNFS_PREFIX = "/$bunfs/";

const SHIMS = [
  { name: "kiri-output", command: "__output" },
  { name: "kiri-recommend", command: "__recommend" },
] as const;

// POSIX single-quoting: the only character needing escape inside single
// quotes is the quote itself, via '\''.
const shellQuote = (value: string): string => `'${value.replaceAll("'", "'\\''")}'`;

const execLine = ({ execPath, main }: ShimTarget, command: string): string => {
  const target = main.startsWith(BUNFS_PREFIX)
    ? shellQuote(execPath)
    : `${shellQuote(execPath)} ${shellQuote(main)}`;
  return `exec ${target} ${command} "$@"`;
};

/**
 * Write the per-run helper shims (`kiri-output`, `kiri-recommend`) into
 * `binDir`, creating the directory if needed. Each shim is a two-line
 * executable `sh` script that execs back into the running kiri build; the
 * runner prepends `binDir` to every spawned step's PATH. Shims live in the
 * run's scratch dir and are regenerated for every run, so they never
 * outlive it.
 */
export function writeRunShims(
  binDir: string,
  target: ShimTarget = { execPath: process.execPath, main: Bun.main },
): void {
  mkdirSync(binDir, { recursive: true });
  for (const shim of SHIMS) {
    const content = `#!/bin/sh\n# Generated by kiri at run start; regenerated every run — edits do not persist.\n${execLine(target, shim.command)}\n`;
    writeFileSync(join(binDir, shim.name), content, { mode: 0o755 });
  }
}
